[build]
  command = "yarn docs:build"
  publish = "docs/.vuepress/dist"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "https://docs.unik-name.com/*"
  to =   "https://docs.unikname.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.unikname.com/integration/connect/apps/*"
  to =   "https://docs.unikname.com/3-unikname-connect/integration-technology/:splat"
  status = 301

[[redirects]]
  from = "https://docs.unikname.com/3-unikname-connect/howto-get-unikname-trust-certificate-organization*"
  to =   "https://docs.unikname.com/3-unikname-connect/howto-create-unikname-trust-certificate-organization:splat"
  status = 301

[[redirects]]
  from = "https://docs.unikname.com/integration/connect/"
  to =   "https://docs.unikname.com/3-unikname-connect/"
  status = 301

[[redirects]]
  from = "https://docs.unikname.com/*"
  to =   "https://help.unikname.com/:splat"
  status = 301
  force = true
